{% set name = "hdbpp-es" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/hdbpp/hdbpp-es/-/archive/{{ version }}/hdbpp-es-{{ version }}.tar.gz
  sha256: eede01e3a0c98a82f68a827578da8ac6030a6de0df84ef1c58d31e4aed76dd71

build:
  number: 0
  skip: true  # [win]
  # Prevent hdb++es-srv.dbg to be modified
  binary_relocation:     # [linux]
    - bin/hdb++es-srv    # [linux]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - pkg-config
  host:
    - cppzmq
    - cpptango
    - omniorb-libs
    - libhdbpp >=2.1.0

test:
  commands:
    - hdb++es-srv --help 2>&1 | grep usage

outputs:                                                # [linux]
  - name: hdbpp-es                                      # [linux]
    files:                                              # [linux]
      - bin/hdb++es-srv                                 # [linux]

  - name: hdbpp-es-dbg                                  # [linux]
    requirements:                                       # [linux]
      host:                                             # [linux]
        # build string must depend on cpptango to have
        # different versions per cpptango
        - cpptango                                      # [linux]
      run:                                              # [linux]
        - {{ pin_subpackage('hdbpp-es', exact=True) }}  # [linux]
    files:                                              # [linux]
      - bin/hdb++es-srv.dbg                             # [linux]
    test:                                               # [linux]
      commands:                                         # [linux]
        - test -f ${PREFIX}/bin/hdb++es-srv.dbg         # [linux]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango device server for the HDB++ Event Subscriber
  dev_url: https://gitlab.com/tango-controls/hdbpp/hdbpp-es
  doc_url: https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/archiving/HDB++.html

extra:
  recipe-maintainers:
    - beenje
