{% set name = "hdbpp-es" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/hdbpp/hdbpp-es/-/archive/{{ version }}/hdbpp-es-{{ version }}.tar.gz
  sha256: bf566f45a339b7c364fcac882fd9dcf2d491daa5a17332896063b11718924b1d

build:
  number: 0
  skip: true  # [win]
  # Prevent hdb++es-srv.dbg to be modified
  binary_relocation:   # [linux]
    - bin/hdb++es-srv    # [linux]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - pkg-config
  host:
    - cppzmq
    - cpptango
    - omniorb-libs
    - libhdbpp >=2.1.0

test:
  commands:
    - hdb++es-srv --help 2>&1 | grep -i usage

outputs:   # [linux]
  - name: hdbpp-es  # [linux]
    files:   # [linux]
      - bin/hdb++es-srv                                 # [linux]

  - name: hdbpp-es-dbg  # [linux]
    requirements:   # [linux]
      host:   # [linux]
        # build string must depend on cpptango to have
        # different versions per cpptango
        - cpptango                                      # [linux]
      run:   # [linux]
        - {{ pin_subpackage('hdbpp-es', exact=True) }}  # [linux]
    files:   # [linux]
      - bin/hdb++es-srv.dbg                             # [linux]
    test:   # [linux]
      commands:   # [linux]
        - test -f ${PREFIX}/bin/hdb++es-srv.dbg         # [linux]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango device server for the HDB++ Event Subscriber
  dev_url: https://gitlab.com/tango-controls/hdbpp/hdbpp-es
  doc_url: https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/archiving/HDB++.html

extra:
  recipe-maintainers:
    - beenje
